
project:
  title: Diddy-VM
  tagline: Learning about Virtual Machines by coding Virtual Machines
  github: diddy-vm

author:
  name: Guy John
  github: rumblesan
  twitter: rumblesan
  email: guy@rumblesan.com

ganalytics: UA-19842221-1

